pub_rate: 1.0 # Optional
base_path: '' # Optional, prepended to all diagnostic output
analyzers:
   Phidget:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Phidget
    analyzers:
      InterfaceKit:
        type: diagnostic_aggregator/GenericAnalyzer
        path: InterfaceKit
        contains: Interface Kit
        remove_prefix: phidgettoROS
      Spatial:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Spatial 
        contains: Spatial
        remove_prefix: phidgettoROS
      Encoders:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Encoders 
        contains: Encoders
        remove_prefix: phidgettoROS
      Servos:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Servos
        contains: Servo
        remove_prefix: PhidgetServo
analyzers:
   Webcam:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Webcam
    analyzers:
      Webcam:
        type: diagnostic_aggregator/GenericAnalyzer
        path: FrontCamera
        find_and_remove_prefix: PTZ
      PanTilt:
        type: diagnostic_aggregator/GenericAnalyzer
        path: corobot_pantilt
        find_and_remove_prefix: PTZ
   GPS:
    type: diagnostic_aggregator/GenericAnalyzer
    path: GPS
    find_and_remove_prefix: corobot_gps
   Hokuyo:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Hokuyo
    find_and_remove_prefix: hokuyo
   SSC32:
    type: diagnostic_aggregator/GenericAnalyzer
    path: SSC32
    find_and_remove_prefix: ssc32control


